sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fusixaf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fusixaf/docker-react npm run test